```{r}
library(tidyverse)
library(cluster)
library(ggbeeswarm)
library(ggrepel)
library(ggalt)

set.seed(1234)
```

```{r}
players <- read_csv("https://dwillis.github.io/sports-data-files/players20.csv")
```

```{r}
playersselected <- players |>
  filter(MP>0) |> filter(Pos == "F") |>
  select(Player, Team, Pos, MP, `FG%`, TRB, BLK, TOV, PTS) |>
  na.omit()
```

```{r}
playersscaled <- playersselected |>
  select(MP, `FG%`, TRB, BLK, TOV, PTS) |>
  mutate_all(scale) |>
  na.omit()
```

```{r}
# function to compute total within-cluster sum of square
wss <- function(k) {
  kmeans(playersscaled, k, nstart = 10 )$tot.withinss
}

# Compute and plot wss for k = 1 to k = 15
k.values <- 1:15

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)

plot(k.values, wss_values,
       type="b", pch = 19, frame = FALSE,
       xlab="Number of clusters K",
       ylab="Total within-clusters sum of squares")
```

```{r}
k8 <- kmeans(playersscaled, centers = 8, nstart = 25)

k8
```

```{r}
playercluster <- data.frame(playersselected, k8$cluster)
```

```{r}
cm <- playercluster |> filter(Player == "Jalen Smith")

cm
```

```{r}
ggplot() +
  geom_point(data=playercluster, aes(x=MP, y=TRB, color=k8.cluster)) +
  geom_point(data=cm, aes(x=MP, y=TRB), color="red")
```

```{r}
big10 <- c("Nebraska Cornhuskers", "Iowa Hawkeyes", "Minnesota Golden Gophers", "Illinois Fighting Illini", "Northwestern Wildcats", "Wisconsin Badgers", "Indiana Hoosiers", "Purdue Boilermakers", "Ohio State Buckeyes", "Michigan Wolverines", "Michigan State Spartans", "Penn State Nittany Lions", "Rutgers Scarlet Knights", "Maryland Terrapins")

playercluster |> filter(k8.cluster == 2) |> filter(Team %in% big10) |> arrange(desc(MP))
```

```{r}
set.seed(1234)

simulations <- rbinom(n = 1000, size = 20, prob = .317)

table(simulations)
```

```{r}
set.seed(1234)

simulations <- rbinom(n = 1000, size = 15, prob = .326)

hist(simulations)
```

```{r}
table(simulations)
```
```{r}
set.seed(1234)

simulations <- rbinom(n = 1000, size = 1, prob = .377)

four_in_a_row <- mean(simulations == 1 & lead(simulations, 1) == 1 & lead(simulations, 2) == 1 & lead(simulations, 3) == 1)

odds <- 1/four_in_a_row
```

```{r}
players <- read_csv("https://thescoop.org/sports-data-files/wbb_players_2023.csv")
```

```{r}
activeplayers <- players |> filter(mp>0) 

activeplayers <- activeplayers |> mutate(tspct=pts/(2*(fga+0.44*fta)))

summary(activeplayers$fga)
```
```{r}
shooters <- activeplayers |> filter(fga > 182)

ggplot() + geom_beeswarm(data=shooters, aes(x=position, y=tspct), color="grey")
```
```{r}
umd <- activeplayers |> 
  filter(team == "Maryland") |> 
  filter(fga>182) |> 
  arrange(desc(tspct))

ggplot() + 
  geom_beeswarm(
    data=shooters, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="grey") + 
  geom_beeswarm(
    data=umd, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="red")
```
```{r}
ggplot() + 
  geom_beeswarm(
    data=shooters, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="grey") + 
  geom_beeswarm(
    data=umd, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="red") +
  geom_text_repel(
    data=umd, 
    aes(x=position, y=tspct, label=player))
```
```{r}
ggplot() + 
  geom_quasirandom(
    data=shooters, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="grey") + 
  geom_quasirandom(
    data=umd, 
    groupOnX=TRUE, 
    aes(x=position, y=tspct), color="red") +
  geom_text_repel(
    data=umd, 
    aes(x=position, y=tspct, label=player))
```

```{r}
ggplot() + 
  geom_jitter(
    data=shooters, 
    aes(x=position, y=tspct), color="grey") + 
  geom_jitter(
    data=umd, 
    aes(x=position, y=tspct), color="red") +
  geom_text_repel(
    data=umd, 
    aes(x=position, y=tspct, label=player))
```

===== 11/30 =====

```{r}
players <- read_csv("https://raw.githubusercontent.com/dwillis/hhs-snapshots/main/data/player_totals_20231130.csv") |> filter(mp > 0)
```

```{r}
ggplot() + geom_point(data=players, aes(x=mp, y=pts))
```

```{r}
topscorers <- players |> filter(pts > 175)

ggplot() + 
  geom_point(data=players, aes(x=mp, y=pts), color="grey") +
  geom_point(data=topscorers, aes(x=mp, y=pts), color="black")
```

```{r}
ggplot() + 
  geom_point(data=players, aes(x=mp, y=pts), color="grey") + 
  geom_point(data=topscorers, aes(x=mp, y=pts), color="black") + 
  geom_encircle(data=topscorers, aes(x=mp, y=pts), s_shape=1, expand=1, colour="red")
```

```{r}
ggplot() + 
  geom_point(data=players, aes(x=mp, y=pts), color="grey") + 
  geom_point(data=topscorers, aes(x=mp, y=pts), color="black") + 
  geom_encircle(data=topscorers, aes(x=mp, y=pts), s_shape=0, expand=0, colour="red")
```

```{r}
ggplot() + 
  geom_point(data=players, aes(x=mp, y=pts), color="grey") + 
  geom_point(data=topscorers, aes(x=mp, y=pts), color="black") + 
  geom_text(data=topscorers, aes(x=mp, y=pts, label=full_name), hjust = 0, vjust=1) +
  geom_encircle(data=topscorers, aes(x=mp, y=pts), s_shape=.5, expand=.03, colour="red")
```

```{r}
ggplot() + 
  geom_point(data=players, aes(x=mp, y=pts), color="grey") + 
  geom_point(data=topscorers, aes(x=mp, y=pts), color="black") + 
  geom_encircle(data=topscorers, aes(x=mp, y=pts), s_shape=.5, expand=.03, colour="red") +
  geom_text(aes(x=275, y=275, label="Top scorers")) + 
  labs(title="Caitlin Clark Alone At Top", subtitle="The Iowa star is by far the top scorer among all NCAA players", x="Minutes", y="Points") + 
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 8), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    )
```

```{r}
players23 <- read_csv("https://thescoop.org/sports-data-files/players23.csv")
```

```{r}
mdtop <- players23 |> filter(Team == "Maryland Terrapins") |> top_n(3, `3PA`)

ggplot() + geom_point(data=players23, aes(x=MP, y=`3PA`), color="grey") + geom_point(data=mdtop, aes(x=MP, y=`3PA`), color="red") + geom_encircle(data=mdtop, aes(x=MP, y=`3PA`), s_shape=.02, expand=.18, colour="red") +
  geom_text(aes(x=400, y=200, label="Maryland's top three shooters")) + 
  labs(title="The Big Three?", subtitle="Maryland's top three point shooters not among the leaders in college basketball ", x="Minutes", y="Three point attempts") + 
  theme_minimal() + 
  theme(
    plot.title = element_text(size = 16, face = "bold"),
    axis.title = element_text(size = 8), 
    plot.subtitle = element_text(size=10), 
    panel.grid.minor = element_blank()
    )
```

===== 12/5 =====

```{r}
logs <- read_csv("https://thescoop.org/sports-data-files/wbblogs24.csv")
rankings <- read_csv("https://thescoop.org/sports-data-files/wbb_rankings.csv")
logs23 <- read_csv("https://thescoop.org/sports-data-files/wbblogs23.csv")
```

```{r}
parity_index24 <- logs |> 
  group_by(Team, Conference) |> 
  summarise(srs_score = mean(TeamSRS), sos_score = mean(TeamSOS)) |> 
  mutate(parity_index = (srs_score + 100) / (sos_score + 100))

parity_index23 <- logs23 |> 
  group_by(Team, Conference) |> 
  summarise(srs_score = mean(TeamSRS), sos_score = mean(TeamSOS)) |> 
  mutate(parity_index = (srs_score + 100) / (sos_score + 100))
```
```{r}
parity_index24 |> 
  filter(Conference == 'Big Ten WBB') |> 
  ggplot() + 
  geom_point(aes(x=srs_score, y = sos_score, label = Team)) +
  geom_text(aes(x=srs_score, y = sos_score, label = Team))
```

```{r}
parity_with_top25 <- parity_index24 |> left_join(rankings, join_by(Team == team))
```

```{r}
combined_data <- bind_rows(parity_index24 |> mutate(season="2024"), parity_index23 |> mutate(season = "2023")) 

result <- combined_data %>%
  group_by(Team) %>%
  summarize(
    Parity_Index_2024 = mean(parity_index[season == "2024"]),
    Parity_Index_2023 = mean(parity_index[season == "2023"])
  ) %>%
  filter(!is.na(Parity_Index_2024)) |> 
  filter(!is.na(Parity_Index_2023)) |>
  ungroup() %>%
  summarise(
    p_value = t.test(Parity_Index_2024, Parity_Index_2023, paired = TRUE)$p.value,
    mean_difference = mean(Parity_Index_2024 - Parity_Index_2023)
  )
```

